// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2lsQQbq4qJVYOVe8eQod6sB8al4yeCfc',
    appId: '1:918081502081:web:6265ab909b886884740680',
    messagingSenderId: '918081502081',
    projectId: 'cre-ad',
    authDomain: 'cre-ad.firebaseapp.com',
    storageBucket: 'cre-ad.appspot.com',
    measurementId: 'G-RZXVHM50QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0gyLXO7Ipi1f8fVGSBRE3XsWShDdiamk',
    appId: '1:918081502081:android:645bc58f310cd3ae740680',
    messagingSenderId: '918081502081',
    projectId: 'cre-ad',
    storageBucket: 'cre-ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8cER3-DvSne31AYDODxYpRhhv8Axyr6c',
    appId: '1:918081502081:ios:b2b7cb1c7b069f93740680',
    messagingSenderId: '918081502081',
    projectId: 'cre-ad',
    storageBucket: 'cre-ad.appspot.com',
    iosClientId: '918081502081-hrncg82hmphp3huahlo6grolegrr5p05.apps.googleusercontent.com',
    iosBundleId: 'com.example.creatorConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8cER3-DvSne31AYDODxYpRhhv8Axyr6c',
    appId: '1:918081502081:ios:bbb1526f935dd52c740680',
    messagingSenderId: '918081502081',
    projectId: 'cre-ad',
    storageBucket: 'cre-ad.appspot.com',
    iosClientId: '918081502081-d9pbrjkd4iihg21l9djk3rcbnrpc9siu.apps.googleusercontent.com',
    iosBundleId: 'com.example.creatorConnect.RunnerTests',
  );
}
